nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.8.6.cjs

packageExtensions:
  "@11ty/eleventy-plugin-bundle@*":
    peerDependencies:
      posthtml: "*"
  "resend@*":
    peerDependencies:
      react: "*"
      react-dom: "*"